# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Make America Smart Again!
email: sharkbeardio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A resource for making smart, informed decisions about candidates and issues.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.smartaga.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SharkBeard
github_username: SharkBeard

# Build settings
markdown: kramdown
sass:
    style: compressed
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
highlight: rouge

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]

theme: jekyll-theme-cayman